name: Update Serial and Create Release

on:
  push:
    branches:
      - main
    paths:
      - 'vATIS Profile - EDGG D-ATIS Development.json'
      
permissions: write-all

jobs:
  update-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.2

      - name: Create Release Version
        run: python .github/workflows/create_release.py

      - name: Commit Release File
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add "vATIS Profile - EDGG D-ATIS Production.json"
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update release version with serial $(date +%Y%m%d)"
            git push
          fi
